In [2]:
import pandas as pd
import json
from IPython.display import display

# from pprint import pprint

### All events analysis

In [ ]:
# clob = pd.read_csv("clob_final.csv")
clob = pd.read_csv("clob_prices_3.csv")
clob.head(10)

                          slub  total     y     n
0    btc-updown-15m-1774254600   1.02  0.51  0.51
1    doge-updown-5m-1774254900   1.02  0.51  0.51
2     eth-updown-5m-1774254600   1.02  0.51  0.51
3    xrp-updown-15m-1774254600   1.02  0.51  0.51
4   hype-updown-15m-1774254600   1.02  0.51  0.51
5    bnb-updown-15m-1774254600   1.02  0.51  0.51
6     bnb-updown-5m-1774254600   1.02  0.51  0.51
7    eth-updown-15m-1774254600   1.02  0.51  0.51
8   doge-updown-15m-1774254600   1.02  0.51  0.51
9    doge-updown-5m-1774254600   1.02  0.51  0.51

In [19]:
clob.sort_values("total")

                                          slub  total      y      n
6110                  sol-updown-5m-1774203300  0.970  0.280  0.690
6115                 sol-updown-15m-1774203300  0.980  0.390  0.590
3688                   cs2-tl1-mglz-2026-03-22  0.990  0.190  0.800
6118                  xrp-updown-5m-1774203300  0.990  0.330  0.660
5700                  sol-updown-5m-1774203900  1.000  0.530  0.470
...                                        ...    ...    ...    ...
4589    mls-fcc-mim-2026-03-22-exact-score-0-1  1.998  0.999  0.999
4605    mls-fcc-mim-2026-03-22-exact-score-3-0  1.998  0.999  0.999
4591    mls-fcc-mim-2026-03-22-exact-score-1-2  1.998  0.999  0.999
4599    mls-fcc-mim-2026-03-22-exact-score-2-3  1.998  0.999  0.999
16230     dogecoin-up-or-down-march-12-10pm-et  1.998  0.999  0.999

[31244 rows x 4 columns]